<?php
// routselect2.php - Converted from routselect2.html
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SLTB-TransitEase</title>
    <link rel="stylesheet" href="routselect2.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Signika+Negative:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

</head>

<body>
      <div class="header">
        <div class="header-main" >
            <form >
                <div class="language">
                <select name="language" id="language">
                  <option value="volvo">Sinhala</option>
                  <option value="saab">English</option>
                </select>
            </div>
              </form>
        <img src="nee.png" alt="Logo" width="100" style="position: absolute;  right: 80%; transform: translateX(-50%);">
        <button class="admin-button" style="position: absolute;  left: 87.5%; transform: translateX(-50%);" onclick="window.location.href='adminlogin.php'">ADMIN LOGIN</button>
        <img src="kisspng-computer-icons-login-management-user-5ae155f3386149.6695613615247170432309-removebg-preview.png" alt="Ad Logo" width="100">
    </div>
    </div>
     <nav class="navbar" >
            <div class="logo">
                <img src="Bus-logo-temokate-on-transparent-background-PNG-removebg-preview.png" alt="Bus Logo">
                <div class="logo-text">SLTB-Transit<span>Ease</span></div>
            </div>            <ul class="nav-links" style="font-size:20px;">
                <li><a href="sltbhome.php">Home</a></li>
                <li><a href="aboutus.php">About Us</a></li>
                <li><a href="#">Schedule</a></li>
                <li><a href="sltbhotline.php">Hotline</a></li>
            </ul>
        </nav>     <div class="container">
      <div class="main-rect">
        <div class="rect1"><p style="padding-left: 92%;"><b id="routeNumber">#Route 35</b></p></div>
        <div class="rect2">
            <div class="seat-selection-header">
                <h2>Select Your Seat</h2>
                <div class="route-info">
                    <p><strong>From:</strong> <span id="fromLocation">-</span> | <strong>To:</strong> <span id="toLocation">-</span> | <strong>Date:</strong> <span id="travelDate">-</span> | <strong>Price:</strong> Rs. <span id="ticketPrice">-</span></p>
                </div>
                <div class="legend">
                    <span class="legend-item"><div class="seat available"></div> Available</span>
                    <span class="legend-item"><div class="seat selected"></div> Selected</span>
                    <span class="legend-item"><div class="seat occupied"></div> Occupied</span>
                </div>
            </div>
            <div class="bus-layout">
                <div class="seat-grid" id="seatGrid">
                    <!-- Seats will be generated by JavaScript -->
                </div>
            </div>
            <div class="selection-info">
                <p>Selected Seats: <span id="selectedSeats">None</span></p>
                <button class="proceed-button" onclick="proceedToPayment()">Proceed to Payment</button>
            </div>
        </div>
        <div class="rect3"></div>
      </div>

    </div>

  <footer class="footer" >
        <div class="footer-column">
            <div class="social-media">
            <ul>
                <li><a href="#"><img src="Images/socialmedea.png" ></a width:100;></li>
              
            </ul>
        </div>
        </div>
        <div class="footer-column">
            <div class="list">
            <ul>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">T&C</a></li>
                <li><a href="#">Contact Us</a></li>
            </ul>
        </div>
        </div>
        <div class="footer-column">
            <div class="logo">
                <img src="Bus-logo-temokate-on-transparent-background-PNG-removebg-preview.png" alt="Bus Logo">
                <div class="logo-text">SLTB-Transit<span>Ease</span></div>
            </div>
            <div class="apex"><p>Team Apex<br>teamapex@gmail.com</p></div>
            
          
          </div>
        <div class="footer-column">
            <div class="footer-sltb">
            <img src="nee.png" alt="SLTB Logo" width="100" >
        </div>
        <div class="new">
            <p><b>Sri Lanka Transport Board</b>
            <br>No. 200, Kirula Road, Colombo 5
            <br>+94(0)11 7706000|+94(0)11 25811120-4
            <br>=94(0)11 2589683|info@sltb.lk</p>
        </div>
        </div>    </footer>    <script>
        let selectedSeats = [];
        const occupiedSeats = [5, 12, 18, 23, 34, 41]; // Example occupied seats

        // Route information from URL parameters
        let routeInfo = {};

        function getURLParameters() {
            const urlParams = new URLSearchParams(window.location.search);
            return {
                routeId: urlParams.get('routeId') || 'R001',
                from: urlParams.get('from') || 'Not specified',
                to: urlParams.get('to') || 'Not specified',
                date: urlParams.get('date') || 'Not specified',
                price: urlParams.get('price') || '0'
            };
        }

        function formatDate(dateString) {
            if (dateString === 'Not specified') return dateString;
            const date = new Date(dateString);
            return date.toLocaleDateString('en-US', { 
                weekday: 'short', 
                month: 'short', 
                day: 'numeric' 
            });
        }

        function getRouteNumberFromId(routeId) {
            const routeMap = {
                'R001': '#Route 35',
                'R002': '#Route 36',
                'R003': '#Route 47',
                'R004': '#Route 52',
                'R005': '#Route 63'
            };
            return routeMap[routeId] || '#Route 35';
        }

        function displayRouteInfo() {
            routeInfo = getURLParameters();
            
            // Update route number
            document.getElementById('routeNumber').textContent = getRouteNumberFromId(routeInfo.routeId);
            
            // Update route details
            document.getElementById('fromLocation').textContent = routeInfo.from;
            document.getElementById('toLocation').textContent = routeInfo.to;
            document.getElementById('travelDate').textContent = formatDate(routeInfo.date);
            document.getElementById('ticketPrice').textContent = routeInfo.price;
        }

        function generateSeats() {
            const seatGrid = document.getElementById('seatGrid');
            
            for (let i = 1; i <= 52; i++) {
                const seat = document.createElement('div');
                seat.className = 'seat';
                seat.id = `seat-${i}`;
                seat.textContent = i;
                
                // Check if seat is occupied
                if (occupiedSeats.includes(i)) {
                    seat.classList.add('occupied');
                } else {
                    seat.classList.add('available');
                    seat.addEventListener('click', () => toggleSeat(i));
                }
                
                seatGrid.appendChild(seat);
            }
        }

        function toggleSeat(seatNumber) {
            const seat = document.getElementById(`seat-${seatNumber}`);
            const seatIndex = selectedSeats.indexOf(seatNumber);
            
            if (seatIndex > -1) {
                // Remove seat from selection
                selectedSeats.splice(seatIndex, 1);
                seat.classList.remove('selected');
                seat.classList.add('available');
            } else {
                // Add seat to selection
                selectedSeats.push(seatNumber);
                seat.classList.remove('available');
                seat.classList.add('selected');
            }
            
            updateSelectedSeatsDisplay();
        }

        function updateSelectedSeatsDisplay() {
            const selectedSeatsElement = document.getElementById('selectedSeats');
            if (selectedSeats.length === 0) {
                selectedSeatsElement.textContent = 'None';
            } else {
                selectedSeatsElement.textContent = selectedSeats.sort((a, b) => a - b).join(', ');
            }
        }        function proceedToPayment() {
            if (selectedSeats.length === 0) {
                alert('Please select at least one seat before proceeding.');
                return;
            }
            
            // Calculate total price
            const totalPrice = parseInt(routeInfo.price) * selectedSeats.length;
            
            // Store booking information
            const bookingData = {
                routeId: routeInfo.routeId,
                routeNumber: getRouteNumberFromId(routeInfo.routeId),
                from: routeInfo.from,
                to: routeInfo.to,
                date: routeInfo.date,
                selectedSeats: selectedSeats,
                seatCount: selectedSeats.length,
                pricePerSeat: routeInfo.price,
                totalPrice: totalPrice
            };
            
            localStorage.setItem('bookingData', JSON.stringify(bookingData));
              // Redirect to payment page with parameters
            const paymentUrl = `payment.php?routeId=${routeInfo.routeId}&from=${encodeURIComponent(routeInfo.from)}&to=${encodeURIComponent(routeInfo.to)}&date=${routeInfo.date}&seats=${selectedSeats.join(',')}&total=${totalPrice}`;
            window.location.href = paymentUrl;
        }        // Initialize page when DOM is loaded
        document.addEventListener('DOMContentLoaded', function() {
            displayRouteInfo();
            generateSeats();
        });
    </script>

</body>

</html>
